PASS_Configuration:
    path: /auth/configuration/sql
    defaults: { _controller: PASSGeneralLogBundle:Configuration:index }
PASS_ConfigurationLdap:
    path: /auth/configuration/ldap
    defaults: { _controller: PASSGeneralLogBundle:Configuration:ldap }
    
PASS_ConfigurationMail:
    path: /auth/configuration/mail
    defaults: { _controller: PASSGeneralLogBundle:Configuration:mail }
PASS_MDP:
    path: /mdp
    defaults: { _controller: PASSGeneralLogBundle:Configuration:mdp }