PASS_AffichageLog:
    path:  /auth/listing
    defaults: { _controller: PASSGestionLogBundle:gestionLog:affichageLog }
PASS_AffichageStat:
    path:  /auth/stat
    defaults: { _controller: PASSGestionLogBundle:statistique:affichageStat }

PASS_Erase:
    path:  /auth/erase/{l}
    defaults: { _controller: PASSGestionLogBundle:gestionLog:Erase }
    
       
PASS_GroupeOrdinateurAdd:
    path:  /auth/groupeOrdinateur/add
    defaults: { _controller: PASSGestionLogBundle:GroupeOrdinateur:groupeOrdinateurAdd }
    
PASS_GroupeOrdinateurModification:
    path: /auth/groupeOrdinateur/modification/{listingId}
    defaults: { _controller:  PASSGestionLogBundle:GroupeOrdinateur:GroupeOrdinateurModification, listingId: 0 }
    requirements:
        listingId: \d+
        
PASS_GroupeOrdinateurDelete:
    path: /auth/groupeOrdinateur/Delete/{groupeId}
    defaults: { _controller:  PASSGestionLogBundle:GroupeOrdinateur:GroupeOrdinateurSupprimer, groupeId: 0 }
    requirements:
        groupeId: \d+       
        
PASS_GroupeOrdinateurListing:
    path: /auth/groupeOrdinateur/{listingId}
    defaults: { _controller:  PASSGestionLogBundle:GroupeOrdinateur:groupeOrdinateurListing, listingId: 0 }
    requirements:
        listingId: \d+
        

Pass_Mail:
    path: /mail
    defaults: { _controller:  PASSGestionLogBundle:EnvoyerMail:index }
    
PASS_statRemove:
    path: /removeStat
    defaults: { _controller:  PASSGestionLogBundle:statistique:RemoveStat }
    