pass_general_log:
    resource: "@PASSGeneralLogBundle/Controller/"
    type:     annotation
    prefix:   /


pass_Authen_log:
    resource: "@PASSAuthentificationLogBundle/Resources/config/routing.yml"
    prefix: /
pass_gestion_log:
    resource: "@PASSGestionLogBundle/Resources/config/routing.yml"
    prefix: /

