services:
    time_authenticator:
        class:     PASS\AuthentificationLogBundle\Security\TimeAuthenticator
        arguments: ["@security.password_encoder"]

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        PASS\AuthentificationLogBundle\Entity\Personne: sha512
    providers:
        
        database:
            entity: { class: PASSAuthentificationLogBundle:Personne, property: username}
        in_memory:
            memory: ~
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    firewalls:
        
        
        
                
        auth_area:
            
            pattern: ^/(login_check|auth/|logout)
            simple_form:
            #form_login:    
                authenticator: time_authenticator
                provider: database
                
                #csrf_provider: form.csrf_provider
                
                
            logout:
                path: /logout
                target: login
           
        
        
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
         
         
        default:
            anonymous: ~
         
    