security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        PASS\AuthentificationLogBundle\Entity\Personne: sha512
    providers:
        pass_provider:
            id: pass_auth_user_provider
        database:
            entity: { class: PASSAuthentificationLogBundle:Personne, property: username }
        in_memory:
            memory: ~
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    firewalls:
        
        login:
            pattern:  ^/demo/secured/login$
            security: false
        secured_area:
            pattern:    ^/demo/secured/
            webservice-login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
                provider: pass_provider
            logout:
                path:   /demo/secured/logout
                target: /demo/
                
        auth_area:
            pattern: ^/(login_check|auth/|logout)
            form_login:
                login_path: login
                check_path: /login_check
                
            logout:
                path: /logout
                target: login
           
        
        
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
         
         
        default:
            anonymous: ~
            
            
    