services:
    time_authenticator:
        class:     PASS\AuthentificationLogBundle\Security\TimeAuthenticator
        arguments: ["@security.password_encoder"]

security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        PASS\AuthentificationLogBundle\Entity\Personne: sha512
    providers:
        main_provider:
            chain :
                providers: [in_memory, database]
        
        database:
            entity: { class: PASSAuthentificationLogBundle:Personne, property: username}
        in_memory:
            memory:
                users:
                    AdminM: { password: stHGdg4MhYOm/OVTWjpMJievIvJqafsQQ3WpWlUNDT6WfHupVWjBQaxdppMQkdCmYSXl6QQQXVYLGL/MDZi5Zw== , roles: 'ROLE_MEMORY'  }
            
    role_hierarchy:
        ROLE_MEMORY:      ROLE_USER
        ROLE_ADMIN:       [ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
      
    firewalls:
        
        
        
                
        auth_area:
            
            pattern: ^/(login_check|auth/|logout)
           #simple_form:
            form_login:    
               # authenticator: time_authenticator
                provider: main_provider
                
                #csrf_provider: form.csrf_provider
                
                
            logout:
                path: /logout
                target: login
           
        
        
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
         
         
        default:
            anonymous: ~
         
    