<?php

namespace PASS\AuthentificationLogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use PASS\AuthentificationLogBundle\Entity\Personne;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Doctrine\ORM\NoResultException;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends EntityRepository implements UserProviderInterface, ContainerAwareInterface {

    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    public function loadUserByUsername($login) {

        $q = $this
                ->createQueryBuilder('i')
                ->select(array('i', 'p'))
                ->leftJoin('i.groupes', 'p')
                //->leftJoin('p.roles', 'r')
                ->where('i.username = :login')
                ->setParameter('login', $login)
                ->getQuery();
        try {
            $user = $q->setMaxResults(1);
        } catch (NoResultException $e) {
            throw new UsernameNotFoundException(sprintf('L\'utilisateur "%s" n\'a pas été trouvé ou n\'est pas actif.', $username), 0, $e);
        }

        return $user->getResult();
    }

    public function loadById($id) {
        $q = $this
                ->createQueryBuilder('i')
                ->select(array('i', 'p'))
                ->leftJoin('i.groupes', 'p')
                //->leftJoin('p.roles', 'r')
                ->where('i.id = :id')
                ->setParameter('id', $id)
                ->getQuery();
        try {
            // La méthode Query::getSingleResult() lance une exception
            // s'il n'y a pas d'entrée correspondante aux critères
            $user = $q->getSingleResult();
        } catch (NoResultException $e) {
            throw new UsernameNotFoundException(sprintf('L\'utilisateur "%s" n\'a pas été trouvé ou n\'est pas actif.', $username), 0, $e);
        }

        return $user;
    }

    public function refreshUser(\Symfony\Component\Security\Core\User\UserInterface $user) {
        $class = get_class($user);
        if (!$this->supportsClass($class)) {
            throw new UnsupportedUserException(
            sprintf(
                    'Instances of "%s" are not supported.', $class
            )
            );
        }
        return $this->loadById($user->getId());
    }

    function supportsClass($class) {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }

    function getAllUser() {
        return $this->createQueryBuilder('p')
                        ->select('p')
                        ->orderBy("p.username")
                        ->getQuery()->execute();
    }
    
    
    function getAllUserNoLdap() {
        return $this->createQueryBuilder('p')
                        ->select('p')
                        ->where("p.ldap = FALSE")
                        ->orderBy("p.username")
                        ->getQuery()->execute();
    }
    function getAllUserLdap() {
        return $this->createQueryBuilder('p')
                        ->select('p')
                        ->where("p.ldap = TRUE")
                        ->orderBy("p.username")
                        ->getQuery()->execute();
    }

     function getUserLdap($username) {
         try {
         $p = $this->createQueryBuilder('p')
                        ->select('p')
                        ->where("p.ldap = TRUE")
                        ->andWhere("p.username = '".$username."'")
                        ->orderBy("p.username")
                        ->getQuery();
        
      
            // La méthode Query::getSingleResult() lance une exception
            // s'il n'y a pas d'entrée correspondante aux critères
         $p->setMaxResults(1);
        } catch (\Exception $e) {
            return null;
            throw new UsernameNotFoundException(sprintf('L\'utilisateur "%s" n\'a pas été trouvé ou n\'est pas actif.', $username), 0, $e);
        }
        return $p->getResult();
    }
    
         public function updateLastLogin($id)
        {
             
         }
}
