## YAML Template.

PASS_AuthentificationLog_homepage:
    path:  /hello
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:index }

PASS_CreationGroupe:
    path: /auth/gestion/groupe/add
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:groupeAdd, listingId: 0 }
    requirements:
        listingId: \d+
PASS_GestionUtilisateur:
    path: /auth/gestion/utilisateur/{listingId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:utilisateurListing,  listingId: 0 }
    requirements:
        listingId: \d+
PASS_GestionGroupe:
    path: /auth/gestion/groupe/{listingId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:groupeListing, listingId: 0 }    
    requirements:
        listingId: \d+
    
PASS_CreationUtilisateur:
    path: /auth/gestion/utilisateur/add
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:utilisateurAdd,  listingId: 0}
    
    
PASS_ModificationUtilisateur:
    path: /auth/gestion/utilisateur/modification/{listingId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:utilisateurModification, listingId: 0 }
    requirements:
        listingId: \d+
PASS_MonCompte:
    path: /auth/monCompte/{listingId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:utilisateurModification, listingId: 0 }
    requirements:
        listingId: \d+
        
PASS_ModificationGroupe:
    path: /auth/gestion/groupe/modification/{listingId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:groupeAdd }
    requirements:
        listingId: \d+
        
        
PASS_SupprimerUtilisateur:
    path: /auth/gestion/utilisateur/supprimer/{personneId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:utilisateurSupprimer, personneId: 0 }
    requirements:
        personneId: \d+     
PASS_SupprimerGroupe:
    path: /auth/gestion/groupe/supprimer/{groupeId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:groupeSupprimer,groupeId: 0 }
    requirements:
        groupeId: \d+    
        
PASS_ChangeMDP:
    path: /auth/gestion/utilisateur/changeMDP/{personneId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:changeMDP,personneId: 0 }
    requirements:
        groupeId: \d+ 
    
PASS_Gestion_ok:
    path: /auth/ok
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:ok }
    

login:
    pattern: /login
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:login }
login_check:
    pattern: /login_check
logout:
    pattern: /logout
    
    
PASS_importLDAP:
    path: /import
    defaults: { _controller: PASSAuthentificationLogBundle:ImportationPersonne:importPersonne }