## YAML Template.


PASS_CreationGroupe:
    path: /auth/gestion/groupe/add
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:groupeAdd, listingId: 0 }
    requirements:
        listingId: \d+
PASS_GestionUtilisateur:
    path: /auth/gestion/utilisateur/{listingId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:utilisateurListing,  listingId: 0 }
    requirements:
        listingId: \d+
PASS_GestionGroupe:
    path: /auth/gestion/groupe/{listingId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:groupeListing, listingId: 0 }    
    requirements:
        listingId: \d+
    
PASS_CreationUtilisateur:
    path: /auth/gestion/utilisateur/add
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:utilisateurAdd,  listingId: 0}
    
    
PASS_ModificationUtilisateur:
    path: /auth/gestion/utilisateur/modification/{listingId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:utilisateurModification, listingId: 0 }
    requirements:
        listingId: \d+
PASS_droitGroupeUtilisateur:
    path: /auth/gestion/droit/utilisateur/{personne}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:roleUser, personne: 0 }
    requirements:
        personne: \d+
PASS_droitGroupe:
    path: /auth/gestion/droit/groupe/{groupe}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:roleGroupe, groupe: 0 }
    requirements:
        groupe: \d+
PASS_MonCompte:
    path: /auth/monCompte
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:MonCompte }
    requirements:
        listingId: \d+
        
PASS_ModificationGroupe:
    path: /auth/gestion/groupe/modification/{listingId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:groupeAdd, listingId: 0  }
    requirements:
        listingId: \d+
        
        
PASS_SupprimerUtilisateur:
    path: /auth/gestion/utilisateur/supprimer/{personneId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:utilisateurSupprimer, personneId: 0 }
    requirements:
        personneId: \d+     
PASS_SupprimerGroupe:
    path: /auth/gestion/groupe/supprimer/{groupeId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:groupeSupprimer,groupeId: 0 }
    requirements:
        groupeId: \d+    
        
PASS_ChangeMDP:
    path: /auth/gestion/utilisateur/changeMDP/{personneId}
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:changeMDP,personneId: 0 }
    requirements:
        groupeId: \d+ 
        
        

        
    
PASS_Gestion_ok:
    path: /auth/ok
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:ok }
    

login:
    pattern: /login
    defaults: { _controller: PASSAuthentificationLogBundle:Authentification:login }
login_check:
    pattern: /login_check
logout:
    pattern: /logout
    
    
PASS_importLDAP:
    path: /auth/import
    defaults: { _controller: PASSAuthentificationLogBundle:ImportationPersonne:importPersonne }
PASS_modificationLDAP:
    path: /auth/ldap/modification/{username}
    defaults: { _controller: PASSAuthentificationLogBundle:ImportationPersonne:ModificationPersonneLdap, username: 0 }
PASS_GestionRole:
    path: /auth/Role
    defaults: { _controller: PASSAuthentificationLogBundle:GestionRole:gestionRole }