## YAML Template.


parameters:
    security.user.provider.pass.service.class: PASS\AuthentificationLogBundle\Security\Core\WebserviceUserProvider
    pass.service.class: PASS\AuthentificationLogBundle\Service\Service
    security.authentication.provider.pass_service.class: PASS\AuthentificationLogBundle\Security\Core\EpsAuthenticationProvider
# src/Acme/MainBundle/Resources/config/services.yml
services:
    # the menu builder service. Can be used for several menus
   

        
    pass_auth_webservice:
        class: %pass.service.class%
    pass_auth_user_provider:
        class: %security.user.provider.pass.service.class%
        arguments: [@pass_auth_webservice, @doctrine.orm.entity_manager]
        
    security.authentication_provider.pass_auth_webservice:
        class: %security.authentication.provider.pass_service.class%
        abstract: true
        public: false
        arguments: [@pass_auth_webservice, @security.user_checker, @security.user_checker,@security.encoder_factory,security.authentication.hide_user_not_found]