## YAML Template.
---
# src/Acme/MainBundle/Resources/config/services.yml
services:
    # the menu builder service. Can be used for several menus
   
    ldap.security.authentication.provider:
        class:  PASS\AuthentificationLogBundle\Security\Authentification\Provider\ldapProvider
        arguments: ['', %kernel.cache_dir%/security/nonces]
    ldap.security.authentication.listener:
        class:  PASS\AuthentificationLogBundle\Security\Authentification\Firewall\ldapListener
        arguments: [@security.context, @security.authentication.manager]